### ISSUE TITLE
pip install error on windows 

### ISSUE THREAD

**Issue by deadmau5v** [Jacksgong/webp-converter#10]
env miniconda
system windows 10
python version 3.12.1

```python
C:\Users\d5v>conda activate

(base) C:\Users\d5v>pip install webp-converter
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting webp-converter
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/fc/cf/da77b6c4640ffdddb7beafcfce27ffd40494acab794bb8d6e7a6473ecea6/webp-converter-4.1.0.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\d5v\AppData\Local\Temp\pip-install-90xws1wh\webp-converter_08e522257aee42b9b6a768e08e7c5f0a\setup.py", line 23, in <module>
          long_description = f.read()
                             ^^^^^^^^
      UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 375: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by deadmau5v** [comment]
```python
with open('README.md', encoding="utf-8") as f:
    long_description = f.read()
```

add `encoding="utf-8"` 😂
