### ISSUE TITLE
Webp Package dependent 

### ISSUE THREAD

**Issue by cololi** [Jacksgong/webp-converter#2]
`-------------------------------------------------------
origin images will be replace with webp images on /home/callkin/tea/dja_callkin/pfmea/static/image
convert for /home/callkin/tea/dja_callkin/pfmea/static/image/background.jpg
Traceback (most recent call last):
  File "/usr/bin/webpc", line 9, in <module>
    load_entry_point('webp-converter==4.0.1', 'console_scripts', 'webpc')()
  File "/usr/lib/python2.7/site-packages/webpc/__init__.py", line 119, in main
    output_data=output_data
  File "/usr/lib/python2.7/site-packages/webpc/__init__.py", line 196, in loop
    output_file_path, is_debug)
  File "/usr/lib/python2.7/site-packages/webpc/converter.py", line 98, in convert
    subprocess.Popen(command, stdout=FNULL, stderr=subprocess.STDOUT).communicate()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`
In CentOS7 I have this error and what can I installed package?

**Comment by ghost** [comment]
You should follow the instructions in the Readme and install _webp_ to your system with whatever dependency manager you have (brew, apt, yarn ... ).

Probably you solved the problem by now but I am just commenting for others that face the same issue.
