### ISSUE TITLE
FileNotFound Error For 'cwwbp'

### ISSUE THREAD

**Issue by nilpatel62** [Jacksgong/webp-converter#4]
origin images will be replace with webp images on /home/embed/OtherProjects/picture
convert for /home/embed/OtherProjects/picture/a.jpg
Traceback (most recent call last):
  File "/home/embed/OtherProjects/picture/enve/bin/webpc", line 11, in <module>
    sys.exit(main())
  File "/home/embed/OtherProjects/picture/enve/lib/python3.5/site-packages/webpc/__init__.py", line 129, in main
    output_data=output_data
  File "/home/embed/OtherProjects/picture/enve/lib/python3.5/site-packages/webpc/__init__.py", line 206, in loop
    output_file_path, is_debug)
  File "/home/embed/OtherProjects/picture/enve/lib/python3.5/site-packages/webpc/__init__.py", line 293, in convert
    subprocess.Popen(command, stdout=FNULL, stderr=subprocess.STDOUT).communicate()
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'cwebp'

**Comment by Macleykun** [comment]
Did you install webp with:
`brew install webp`
or if you prefer to install it with apt:
`sudo apt install webp -y`
